source 'https://rubygems.org'

gem 'sinatra', '~> 4.0.0'
gem "puma", "~> 6.4"
gem "rackup", "~> 2.1"

group :test, :development do
  gem "rack-test", "~> 2.0.2"
  gem "rack-rest-rspec", "~> 0.0.3"
  gem 'rspec', '~> 3.10.0'
  gem 'rake', '~> 13.0'
end