source 'https://rubygems.org'

gem 'puma', '~> 6.4'
gem 'rackup', '~> 2.1'
gem 'sinatra', '~> 4.0.0'

group :test, :development do
  gem 'rack-rest-rspec', '~> 0.0.3'
  gem 'rack-test', '~> 2.0.2'
  gem 'rake', '~> 13.0'
  gem 'rspec', '~> 3.10.0'
end
